// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDczGQzO_DjABxqEdtdkkPQ9U4fKqpXjc',
    appId: '1:534674979923:web:0411451900a9ad32595aa6',
    messagingSenderId: '534674979923',
    projectId: 'dawak-5cd94',
    authDomain: 'dawak-5cd94.firebaseapp.com',
    storageBucket: 'dawak-5cd94.firebasestorage.app',
    measurementId: 'G-RSY0GR2WRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQUTkQD1B5T7rAJcBgdY2OA-eGwxEP_Y',
    appId: '1:534674979923:android:ec226f14d0b498ae595aa6',
    messagingSenderId: '534674979923',
    projectId: 'dawak-5cd94',
    storageBucket: 'dawak-5cd94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwRhYxBpDD1D9aUukOzdhHMJrcPdvWdyg',
    appId: '1:534674979923:ios:2dc4d71902e81ddb595aa6',
    messagingSenderId: '534674979923',
    projectId: 'dawak-5cd94',
    storageBucket: 'dawak-5cd94.firebasestorage.app',
    iosBundleId: 'com.example.dawak',
  );
}
